### ISSUE TITLE
The website is blocked by the chinese goverment

### ISSUE THREAD

**Issue by lucacastelnuovo** [sunwei/json-editor-online-command-line-tool#1]
![schermafbeelding 2019-03-02 om 10 44 45 am](https://user-images.githubusercontent.com/26206253/53680189-3584aa00-3cd8-11e9-9c82-3e012adeb780.png)
![schermafbeelding 2019-03-02 om 10 44 41 am](https://user-images.githubusercontent.com/26206253/53680190-3584aa00-3cd8-11e9-97d7-e2d2552f60b1.png)

**Comment by sunzhongmou** [comment]
Thanks a lot, just deploy to github page and support https.
Please refer to: https://jsoneditoronline.cn/
And this tool has upgraded to 4.0, have a try :)

**Comment by lucacastelnuovo** [comment]
Thnx it's solved. 👍
